.\" This document is in the public domain.
.\" vim: fdm=marker cms=.\\"\ %s
.
.\" FRONT MATTER {{{
.Dd Mar 4, 2015
.Os
.Dt HAVEOPT 1
.
.Sh NAME
.Nm haveopt
.Nd Option parser for sh
.\" FRONT MATTER }}}
.
.\" SYNOPSIS {{{
.Sh SYNOPSIS
.Nm
.Fl h | \-help
.Nm
.Ar OPTIND
.Ar OPTNAME
.Ar OPTARG
.Op Ar OPTSPEC Ns ...
.Li --
.Li Qq $@
.Nm
.Ar OPTIND
.Ar OPTNAME
.Ar OPTARG
.Op Ar OPTSPEC Ns ...
.Li --
.Op Ar ARG Ns ...
.\" SYNOPSIS }}}
.
.\" DESCRIPTION {{{
.Sh DESCRIPTION
.Nm
is a
.Xr sh 1 Ns -compatible
argument parser similar to
.Ic getopts
with added support for long options, as in GNU
.Xr getopt 1 .
Like the POSIX
.Ic getopts ,
.Nm
allows for options requiring
.Em option-arguments .
Unlike GNU
.Ic getopt ,
.Nm
does not permit
optional
.Em option-arguments .
.Pp
Each time
.Nm
is invoked, it shall place the name of the next
.Em option
in the shell
parameter named in the
.Ar OPTNAME
operand and the count of arguments
processed so far in the shell parameter named in
.Ar OPTIND .
If the name reported in
.Ar OPTNAME
requires an
.Em option-argument
according to the
.Ar OPTSPEC Ns ...
list, the shell parameter named in the
.Ar OPTARG
operand shall contain according value.
Otherwise, the shell parameter named in
.Ar OPTARG
shall be unset.
.Pp
If an option not contained in the
.Ar OPTSPEC Ns ...
list is found where an option is expected,
the shell parameter specified by
.Ar OPTNAME
shall be set to the
.Aq Li question-mark
.Pq Sq Li \&?
character.
Shell parameter given in
.Ar OPTARG
shall be set to the option found.
.Pp
When the end of options is encountered, the
.Nm
utility shall exit with a return value greater than zero;
the shell parameter named in
.Ar OPTIND
shall be set to the index of the last option or
.Em option-argument ,
or 0 if there are no such arguments;
the parameter given in
.Ar OPTNAME
shall be set to the
.Aq question-mark
character.
Any of the following shall identify the end of options:
the first "--" argument that is not an
.Em option-argument ,
finding an argument that is not an
.Em option-argument
and does not begin with a '-', or encountering an error.
.Pp
Note: the shell parameter named in
.Ar OPTIND
assumes values that are
one less than what
.Ic getopts
would set
.Ar OPTIND
to.
This is for two reasons.
First, there's no way a non-privileged shell script could
fulfill this promise:
.Bd -ragged -offset "xx"
Whenever the shell is invoked, OPTIND shall be initialized to 1.
.Ed
.Pp
Second, the client code is not forced into funky
.Sy Arithmetic Expansion
syntax, plain
.Li shift $OPTIND
will suffice to remove all
.Em options
and
.Em option-arguments
from
.Li $@ .
.Pp
.Nm
is implemented as a
.Xr sh 1
function, loaded into a shell process with
.Bd -literal
  . haveopt.sh

.Ed
.Pa haveopt.sh
must be in
.Ev $PATH
for this to work.
.
.Ss Options
.Bl -tag -width "xx"
. It Fl h , Fl \-help
Display usage string.
.El
.
.Ss Operands
.Bl -tag -width "xx" -compact
. It Ar OPTIND
Name of the shell parameter used to communicate the number of
.Em options
and
.Em option-arguments
processed so far.
. It Ar OPTNAME
Name of the shell parameter used to communicate the
.Em option
extracted.
. It Ar OPTARG
Name of the shell parameter used to communicate the
.Em option-argument
extracted.
. It Ar OPTSPEC
A valid
.Em option
name without the leading dashes.
If the
.Em option
requires an
.Em option-argument ,
.Ar OPTSPEC
should end with
.Ql = .
.Pp
Applications shall make sure that parameter names passed in the
.Ar OPTIND ,
.Ar OPTNAME
and
.Ar OPTARG
operands do not begin with
.Qq Li haveopt_ .
.El
.\" }}}
.
.\" FILES {{{
.\" .Sh FILES
.\" }}}
.
.\" EXIT STATUS {{{
.Sh EXIT STATUS
.Ex -std
.\" }}}
.
.\" EXAMPLES {{{
.Sh EXAMPLES
This example demonstrates both short and long options,
each with and without an
.Em option-argument :
.Bd -literal -offset "xx"
o_compression=gzip
o_filesfrom=
i=0
while haveopt i opt arg J xz T= files-from= -- "$@"
do
  case $opt in
  J|xz)
    o_compression=xz
  ;;
  T|files-from)
    o_filesfrom="$arg"
  ;;
  ?)
    printf "Usage: %s: [-J|--xz] [-T FILE|--files-from=FILE] operands\\n" $0
    exit 2
  ;;
  esac
done
printf "Use %s (de)compression\\n" "$o_compression"
if [ ! -z "$o_filesfrom" ]; then
  printf 'Get pathnames to extract from "%s"\\n' "$o_filesfrom"
fi
shift $i
printf "Remaining arguments are: %s\\n" "$*"
.Ed
.\" }}}
.
.\" SEE ALSO {{{
.Sh SEE ALSO
.Xr getopt 1 ,
.Xr getopts 1 ,
.Xr sh 1 .
.\" }}}
.
.\" STANDARDS {{{
.Sh STANDARDS
.Dq IEEE Std 1003.1-2008/Cor 1-2013
aka
.Dq POSIX.1-2013
aka
.Dq SUSv4TC1
aka
.Dq The Open Group Base Specifications Issue 7 .
.Pp
.Nm
is aligned with the definitions laid out in
.Dq XBD Utility Syntax Guidelines ,
namely guidelines 4-7,9-11,14, with modifications as noted:
.Bl -tag -width "xx"
.It Guideline 4:
Short options must be preceded by the '-' delimiter character.
Long options must be preceded by the '--' delimiter string.
.It Guideline 5:
One or more short options without
.Em option-arguments ,
followed by at most one short option that takes an
.Em option-argument ,
should be accepted when grouped behind one '-' delimiter.
.It Guideline 6:
Each short option and
.Em option-argument
should be a separate argument,
.Nm
also permits applications to specify the option and
.Em option-argument
in the same argument string without
intervening
.Li <blank>
characters.
.It Guideline 7:
.Em Option-arguments
cannot not be optional.
.It Guideline 9:
All options must precede operands on the command line.  Option
processing stops at the first argument that is neither an option
nor an
.Em option-argument .
.It Guideline 10:
The first
.Li --
argument that is not an
.Em option-argument
is accepted as a delimiter indicating the end of options.
Any following arguments are treated as operands, even if they
begin with the '-' character.
.It Guideline 11:
The order of different options relative to one another does not
matter to
.Nm .
Applications are free to ascribe meaning to option ordering.
.It Guideline 14:
If an argument can be identified according to Guidelines 3
through 10 as an option, or as a group of options without
.Em option-arguments
behind one '-' delimiter, then it is treated
as such.
.\" }}}
.
.\" AUTHORS {{{
.Sh AUTHORS
.An Roman Neuhauser Aq Mt neuhauser+haveopt@sigpipe.cz
.Lk https://github.com/roman-neuhauser/haveopt/
.\" AUTHORS }}}
.
.\" BUGS {{{
.Sh BUGS
No doubt plentiful.
Please report them at
.Lk https://github.com/roman-neuhauser/haveopt/issues
.\" BUGS }}}
